name: staffsync
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  video_player: ^2.6.0
  chewie: ^1.13.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  flutter_slidable: ^4.0.1
  google_nav_bar: ^5.0.7
  share_plus: ^7.2.1
  syncfusion_flutter_pdfviewer: ^31.1.19
  path_provider: ^2.1.4
  photo_view: ^0.14.0
  cached_network_image: ^3.3.0
  freezed_annotation: ^3.1.0
  riverpod: ^3.0.0
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  readmore: ^3.0.0
  comment_tree: ^0.3.0
  flutter_html: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.1.0
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  package_info_plus: ^8.3.1
  latlong2: ^0.9.0
  table_calendar: ^3.2.0
  flutter_staggered_animations: ^1.1.1
  intl: ^0.20.2
  local_auth: ^2.2.0
  socket_io_client: ^3.1.2
  flutter_chat_ui: ^2.9.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/location.png
